Repository Supergecki/LaTriX, pull requests merged in 2024-07, with the labels that each got.

#16 Create dotnet-CI.yml
  .github/workflows/dotnet-CI.yml
Labels: Roadmap, Repository

#17 LaTeXConverter class
  src/LaTriX.sln
  src/LaTriXLib/LaTeXConverterClass.cs
  src/LaTriXLib/LaTriXLib.csproj
  src/LaTriXLibTests/LaTriXLibTests.csproj
  src/LaTriXLibTests/UnitTestLaTeXConverter.cs
  src/LaTriXLibTests/test_strings.txt
Labels: Roadmap, Backend

#21 Doxy comments
  src/LaTriXLib/LaTeXConverterClass.cs
  src/LaTriXLibTests/UnitTestLaTeXConverter.cs
Labels: documentation, Roadmap, Backend

#25 Combined
  .github/workflows/Doxygen.yml
  Doxyfile
  src/mainpage.md
Labels: documentation, Roadmap

#26 NuGet: Package-Verwaltung einrichten
  README.md
  src/LaTriXLib/LaTriXLib.csproj
Labels: Roadmap, Repository

#29 Tutorial readme polish
  README.md
  examples/GenerateLaTeXCodes.csproj
  examples/GenerateLaTeXCodes.sln
  examples/Program.cs
  examples/TeXCodes.tex
Labels: documentation, Roadmap, Repository

#28 Test für GUI mit WFA .NET Framework
  .gitignore
  src/GUI/App.config
  src/GUI/Form1.Designer.cs
  src/GUI/Form1.cs
  src/GUI/Form1.resx
  src/GUI/LaTriX.csproj
  src/GUI/Program.cs
  src/GUI/Properties/Resources.Designer.cs
  src/GUI/Properties/Resources.resx
  src/GUI/Properties/Settings.Designer.cs
  src/GUI/Properties/Settings.settings
  src/GUI/Resources/ArrowNachLatex.png
  src/GUI/Resources/LATRIX.ico
  src/LaTriX.sln
Labels: Roadmap, GUI

#32 Updated Namespace
  src/GUI/Form1.Designer.cs
  src/GUI/Form1.cs
  src/GUI/LaTriXGUI.csproj
  src/GUI/Program.cs
  src/GUI/Properties/Resources.Designer.cs
  src/GUI/Properties/Settings.Designer.cs
  src/LaTriX.sln
Labels: Roadmap, GUI

#34 Anmerkung in Readme einfügen
  README.md
Labels: documentation, Roadmap, GUI
